name: stardust
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.22.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.13.0
  google_sign_in: 6.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true



